### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by organize** [joonasil/Miinaharava#1]
<h2> Yleistä </h2>
<i>Ladattu: 22:43</i>
* Sisennykset tehty hyvin. Välillä outoja tyhjiä rivejä sattumanvaraisesti, mutta ei haitaksi koodin luettavuuden puolesta.
* Osa koodista epäsäännöllisesti nimettyä. Välillä vaihtuu kieli, `camelCase` ja loogisuus `(tagx, tagy, printW, cardx, file1, filex)` jne.
* Paketointi loogista.
* Koodi luettavaa.

<h2> Database </h2>
* On hitusen vaistonvastaista kutsua `Database.loadNewDataBase`. Vaikkakin tämä tuo selkeyttä, ei `Database.load` olisi mielestäni yhtään huonompi ratkaisu. Sama kohdistuu metodiin `saveDatabase`. Koska Database on itse tietokannan instanssi, voisi `loadNewDataBase` ja `saveDatabase` refaktoroida toiseen luokkaan, tai vaihtoehtoisesti muuttaa nimeämisiä.
* Metodiin `loadNewDataBase` tulisi lisätä [finally](https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html), koska virheen sattuessa `PrintWriter `-instanssi jää eloon. 
 * Metodin sisäiset muuttujat voitaisiin refaktoroida esim. näihin:
  * `printW` -> `writer`
  * `connectionx` -> `connection`
  * `tagx` -> `tag`

<h2> Card </h2>
* Viittaukset luokan sisällä itseensä konstruktorin ulkopuolella `this`-avainsanalla on turhaa, ellei 
  * a) parametrillä ole sama nimi kuin jollain luokkamuttujalla
  * b) täydy viitata itseensä kokonaisuutena
  * c) täydy kutsua luokan konstruktoria
* Luokan jäsenet on oikeassa järjestyksessä.
* Sisennys on hyvälaatuista.
* `equals`-metodi ei tarkista, onko sille annettava parametri tyyppiä `Card`

<h2> Muut </h2>
<i> `CardStats` </i>
* Näyttää siltä, että `practiceTimes` voitaisiin korvata `howfast.size()`
* Sisennykset ja järjestys edelleen oikea.
* Nimeämisissä epäsäännöllisyyksiä. Camelcase vaihtelee, `howfast` ei kertoisi muuttujan tyyppiä tietämättömälle, että kyseessä on lista. `times, results`

<i>`Tag`</i>
* `equals` ei tarkista parametrin olevan `Tag`-instanssi.
* `toString()` ja `getNimi()` tekevät täysin saman asian.

<h2> Testit </h2>
* Testit melko kattavia, testaavat olennaisen funktionaalisuuden ja suoriutuvat.

**Comment by joonasil** [comment]
Nyt kyllä vaikuttaa siltä että olet katsonut jonkun muun koodia koska en yhtään osaa sanoa mistä tulee card tai database??

**Comment by organize** [comment]
Oho :D Joo nyt tuli väärään osotteeseen, pahoitteluni!
